[package]
name = "rust-jni-java-dylib"
version = "0.1.0"
authors = ["Monnoroch <monnoroch@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
rust-jni-java-lib = { path = "../../java-lib" }
