[package]
name = "rust-jni-java-lib"
version = "0.1.0"
authors = ["Monnoroch <monnoroch@gmail.com>"]
edition = "2021"

[dependencies]
rust-jni = { path = "../../rust-jni" }
jni-sys = "0.3.0"

[dev-dependencies]
rust-jni-java-dylib = { path = "./dylib" }

